// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Resource struct {
	Count   int       `json:"count"`
	Results []*Result `json:"results"`
}

type Result struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}
